{% set name = "chxtools" %}
{% set version = "3.0.2" %}
{% set sha256 = "1d6bb5516c413f85f6502850b4e5563dc899d682adeb4aa242e1525ba59efce1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-CHX/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python !=3.9.5
    - pip
  run:
    - python !=3.9.5
    - databroker
    - eiger-io
    - matplotlib
    - numpy
    - pyepics
    - pymongo
    - scikit-beam
    - scikit-image
    - scipy

test:
  imports:
    - chxtools
    - chxtools._version
    - chxtools.attfuncs
    - chxtools.attfuncs2
    - chxtools.bpm_stability
    - chxtools.chx_utilities
    - chxtools.chx_wrapper
    # The imports below attempts to create a databroker instance with the 'chx'
    # catalog config, so excluding it from this simple test.
    # - chxtools.handlers
    # - chxtools.plot_sid
    - chxtools.pv_explorer
    - chxtools.transfuncs
    - chxtools.xfuncs

about:
  home: https://github.com/NSLS-II-CHX/chxtools
  license: BSD
  license_file: LICENSE
  summary: |
      Repository for data collection and analysis scripts that are useful at
      the CHX beamline at NSLS-II (11-id).
